CREATE TABLE demographics.demographic_data_by_711 AS (
WITH buffer AS (
  --create buffer shapes around points
  SELECT 
    gid, 
    ST_Buffer(geom::geography,100) AS geom 
  FROM demographics.manhattan_711
), transform AS (
  --convert the buffer from geography to geometry
  SELECT 
    gid, 
    ST_Transform(geom::geometry, 4269) AS geom
  FROM buffer
), weight AS (
  --create the weighting based on the intersection area
  SELECT 
    t.gid AS gid, 
    dp1.geoid10 AS geoid10,
    ST_Area(ST_Intersection(t.geom,dp1.geom))/ST_Area(t.geom) AS weight
  FROM transform AS t
  INNER JOIN demographics.dp1 AS dp1
    ON ST_Intersects(t.geom, dp1.geom)
  ORDER BY gid, geoid10
), dem_raw_counts AS (
  SELECT 
    w.gid gid, 
    ROUND(SUM(dp1.total_pop*w.weight))::numeric AS total_pop,
    ROUND(SUM(dp1.total_under_5 * w.weight))::numeric AS total_under_5,
    ROUND(SUM(dp1.total_5_9 * w.weight))::numeric AS total_5_9,
    ROUND(SUM(dp1.total_10_14 * w.weight))::numeric AS total_10_14,
    ROUND(SUM(dp1.total_15_19 * w.weight))::numeric AS total_15_19,
    ROUND(SUM(dp1.total_20_24 * w.weight))::numeric AS total_20_24,
    ROUND(SUM(dp1.total_25_29 * w.weight))::numeric AS total_25_29,
    ROUND(SUM(dp1.total_30_34 * w.weight))::numeric AS total_30_34,
    ROUND(SUM(dp1.total_35_39 * w.weight))::numeric AS total_35_39,
    ROUND(SUM(dp1.total_40_44 * w.weight))::numeric AS total_40_44,
    ROUND(SUM(dp1.total_45_49 * w.weight))::numeric AS total_45_49,
    ROUND(SUM(dp1.total_50_54 * w.weight))::numeric AS total_50_54,
    ROUND(SUM(dp1.total_55_59 * w.weight))::numeric AS total_55_59,
    ROUND(SUM(dp1.total_60_64 * w.weight))::numeric AS total_60_64,
    ROUND(SUM(dp1.total_65_69 * w.weight))::numeric AS total_65_69,
    ROUND(SUM(dp1.total_70_74 * w.weight))::numeric AS total_70_74,
    ROUND(SUM(dp1.total_75_79 * w.weight))::numeric AS total_75_79,
    ROUND(SUM(dp1.total_80_84 * w.weight))::numeric AS total_80_84,
    ROUND(SUM(dp1.total_85_over * w.weight))::numeric AS total_85_over,
    ROUND(SUM(dp1.total_male * w.weight))::numeric AS total_male,
    ROUND(SUM(dp1.male_under_5 * w.weight))::numeric AS male_under_5,
    ROUND(SUM(dp1.male_5_9 * w.weight))::numeric AS male_5_9,
    ROUND(SUM(dp1.male_10_14 * w.weight))::numeric AS male_10_14,
    ROUND(SUM(dp1.male_15_19 * w.weight))::numeric AS male_15_19,
    ROUND(SUM(dp1.male_20_24 * w.weight))::numeric AS male_20_24,
    ROUND(SUM(dp1.male_25_29 * w.weight))::numeric AS male_25_29,
    ROUND(SUM(dp1.male_30_34 * w.weight))::numeric AS male_30_34,
    ROUND(SUM(dp1.male_35_39 * w.weight))::numeric AS male_35_39,
    ROUND(SUM(dp1.male_40_44 * w.weight))::numeric AS male_40_44,
    ROUND(SUM(dp1.male_45_49 * w.weight))::numeric AS male_45_49,
    ROUND(SUM(dp1.male_50_54 * w.weight))::numeric AS male_50_54,
    ROUND(SUM(dp1.male_55_59 * w.weight))::numeric AS male_55_59,
    ROUND(SUM(dp1.male_60_64 * w.weight))::numeric AS male_60_64,
    ROUND(SUM(dp1.male_65_69 * w.weight))::numeric AS male_65_69,
    ROUND(SUM(dp1.male_70_74 * w.weight))::numeric AS male_70_74,
    ROUND(SUM(dp1.male_75_79 * w.weight))::numeric AS male_75_79,
    ROUND(SUM(dp1.male_80_84 * w.weight))::numeric AS male_80_84,
    ROUND(SUM(dp1.male_85_over * w.weight))::numeric AS male_85_over,
    ROUND(SUM(dp1.total_female * w.weight))::numeric AS total_female,
    ROUND(SUM(dp1.female_under_5 * w.weight))::numeric AS female_under_5,
    ROUND(SUM(dp1.female_5_9 * w.weight))::numeric AS female_5_9,
    ROUND(SUM(dp1.female_10_14 * w.weight))::numeric AS female_10_14,
    ROUND(SUM(dp1.female_15_19 * w.weight))::numeric AS female_15_19,
    ROUND(SUM(dp1.female_20_24 * w.weight))::numeric AS female_20_24,
    ROUND(SUM(dp1.female_25_29 * w.weight))::numeric AS female_25_29,
    ROUND(SUM(dp1.female_30_34 * w.weight))::numeric AS female_30_34,
    ROUND(SUM(dp1.female_35_39 * w.weight))::numeric AS female_35_39,
    ROUND(SUM(dp1.female_40_44 * w.weight))::numeric AS female_40_44,
    ROUND(SUM(dp1.female_45_49 * w.weight))::numeric AS female_45_49,
    ROUND(SUM(dp1.female_50_54 * w.weight))::numeric AS female_50_54,
    ROUND(SUM(dp1.female_55_59 * w.weight))::numeric AS female_55_59,
    ROUND(SUM(dp1.female_60_64 * w.weight))::numeric AS female_60_64,
    ROUND(SUM(dp1.female_65_69 * w.weight))::numeric AS female_65_69,
    ROUND(SUM(dp1.female_70_74 * w.weight))::numeric AS female_70_74,
    ROUND(SUM(dp1.female_75_79 * w.weight))::numeric AS female_75_79,
    ROUND(SUM(dp1.female_80_84 * w.weight))::numeric AS female_80_84,
    ROUND(SUM(dp1.female_85_over * w.weight))::numeric AS female_85_over,
    ROUND(SUM(dp1.median_age * w.weight))::numeric AS median_age,
    ROUND(SUM(dp1.median_age_male * w.weight))::numeric AS median_age_male,
    ROUND(SUM(dp1.median_age_female * w.weight))::numeric AS median_age_female,
    ROUND(SUM(dp1.total_pop_over_16 * w.weight))::numeric AS total_pop_over_16,
    ROUND(SUM(dp1.total_male_over_16 * w.weight))::numeric AS total_male_over_16,
    ROUND(SUM(dp1.total_female_over_16 * w.weight))::numeric AS total_female_over_16,
    ROUND(SUM(dp1.total_pop_over_18 * w.weight))::numeric AS total_pop_over_18,
    ROUND(SUM(dp1.total_male_over_18 * w.weight))::numeric AS total_male_over_18,
    ROUND(SUM(dp1.total_female_over_18 * w.weight))::numeric AS total_female_over_18,
    ROUND(SUM(dp1.total_pop_over_21 * w.weight))::numeric AS total_pop_over_21,
    ROUND(SUM(dp1.total_male_over_21 * w.weight))::numeric AS total_male_over_21,
    ROUND(SUM(dp1.total_female_over_21 * w.weight))::numeric AS total_female_over_21,
    ROUND(SUM(dp1.total_pop_over_62 * w.weight))::numeric AS total_pop_over_62,
    ROUND(SUM(dp1.total_male_over_62 * w.weight))::numeric AS total_male_over_62,
    ROUND(SUM(dp1.total_female_over_62 * w.weight))::numeric AS total_female_over_62,
    ROUND(SUM(dp1.total_pop_over_65 * w.weight))::numeric AS total_pop_over_65,
    ROUND(SUM(dp1.total_male_over_65 * w.weight))::numeric AS total_male_over_65,
    ROUND(SUM(dp1.total_female_over_65 * w.weight))::numeric AS total_female_over_65,
    ROUND(SUM(dp1.total_pop2 * w.weight))::numeric AS total_pop2,
    ROUND(SUM(dp1.pop_oneRace * w.weight))::numeric AS pop_oneRace,
    ROUND(SUM(dp1.pop_oneRace_white * w.weight))::numeric AS pop_oneRace_white,
    ROUND(SUM(dp1.pop_oneRace_aa * w.weight))::numeric AS pop_oneRace_aa,
    ROUND(SUM(dp1.pop_oneRace_aian * w.weight))::numeric AS pop_oneRace_aian,
    ROUND(SUM(dp1.pop_oneRace_asian * w.weight))::numeric AS pop_oneRace_asian,
    ROUND(SUM(dp1.pop_oneRace_asian_asianIndian * w.weight))::numeric AS pop_oneRace_asian_asianIndian,
    ROUND(SUM(dp1.pop_oneRace_asian_chinese * w.weight))::numeric AS pop_oneRace_asian_chinese,
    ROUND(SUM(dp1.pop_oneRace_asian_filipino * w.weight))::numeric AS pop_oneRace_asian_filipino,
    ROUND(SUM(dp1.pop_oneRace_asian_japanese * w.weight))::numeric AS pop_oneRace_asian_japanese,
    ROUND(SUM(dp1.pop_oneRace_asian_korean * w.weight))::numeric AS pop_oneRace_asian_korean,
    ROUND(SUM(dp1.pop_oneRace_asian_vietnamese * w.weight))::numeric AS pop_oneRace_asian_vietnamese,
    ROUND(SUM(dp1.pop_oneRace_asian_other * w.weight))::numeric AS pop_oneRace_asian_other,
    ROUND(SUM(dp1.pop_oneRace_nhopi * w.weight))::numeric AS pop_oneRace_nhopi,
    ROUND(SUM(dp1.pop_oneRace_nhopi_nh * w.weight))::numeric AS pop_oneRace_nhopi_nh,
    ROUND(SUM(dp1.pop_oneRace_nhopi_guam * w.weight))::numeric AS pop_oneRace_nhopi_guam,
    ROUND(SUM(dp1.pop_oneRace_nhopi_samoan * w.weight))::numeric AS pop_oneRace_nhopi_samoan,
    ROUND(SUM(dp1.pop_oneRace_nhopi_opi * w.weight))::numeric AS pop_oneRace_nhopi_opi,
    ROUND(SUM(dp1.pop_oneRace_other * w.weight))::numeric AS pop_oneRace_other,
    ROUND(SUM(dp1.pop_twoRaceOrMore * w.weight))::numeric AS pop_twoRaceOrMore,
    ROUND(SUM(dp1.pop_twoRaceOrMore_whiteAian * w.weight))::numeric AS pop_twoRaceOrMore_whiteAian,
    ROUND(SUM(dp1.pop_twoRaceOrMore_whiteAsian * w.weight))::numeric AS pop_twoRaceOrMore_whiteAsian,
    ROUND(SUM(dp1.pop_twoRaceOrMore_whiteAA * w.weight))::numeric AS pop_twoRaceOrMore_whiteAA,
    ROUND(SUM(dp1.pop_twoRaceOrMore_whiteOther * w.weight))::numeric AS pop_twoRaceOrMore_whiteOther,
    ROUND(SUM(dp1.whiteAloneOrCombo * w.weight))::numeric AS whiteAloneOrCombo,
    ROUND(SUM(dp1.aaAloneOrCombo * w.weight))::numeric AS aaAloneOrCombo,
    ROUND(SUM(dp1.aianAloneOrCombo * w.weight))::numeric AS aianAloneOrCombo,
    ROUND(SUM(dp1.asianAloneOrCombo * w.weight))::numeric AS asianAloneOrCombo,
    ROUND(SUM(dp1.nhopiAloneOrCombo * w.weight))::numeric AS nhopiAloneOrCombo,
    ROUND(SUM(dp1.otherAloneOrCombo * w.weight))::numeric AS otherAloneOrCombo,
    ROUND(SUM(dp1.total_pop3 * w.weight))::numeric AS total_pop3,
    ROUND(SUM(dp1.total_hispAnyRace * w.weight))::numeric AS total_hispAnyRace,
    ROUND(SUM(dp1.hispAnyRace_mexican * w.weight))::numeric AS hispAnyRace_mexican,
    ROUND(SUM(dp1.hispAnyRace_puertoRican * w.weight))::numeric AS hispAnyRace_puertoRican,
    ROUND(SUM(dp1.hispAnyRace_cuban * w.weight))::numeric AS hispAnyRace_cuban,
    ROUND(SUM(dp1.hispAnyRace_otherHisp * w.weight))::numeric AS hispAnyRace_otherHisp,
    ROUND(SUM(dp1.total_nonHisp * w.weight))::numeric AS total_nonHisp,
    ROUND(SUM(dp1.total_pop4 * w.weight))::numeric AS total_pop4,
    ROUND(SUM(dp1.total_hisp * w.weight))::numeric AS total_hisp,
    ROUND(SUM(dp1.hisp_whiteAlone * w.weight))::numeric AS hisp_whiteAlone,
    ROUND(SUM(dp1.hisp_aaAlone * w.weight))::numeric AS hisp_aaAlone,
    ROUND(SUM(dp1.hisp_aianAlone * w.weight))::numeric AS hisp_aianAlone,
    ROUND(SUM(dp1.hisp_asianAlone * w.weight))::numeric AS hisp_asianAlone,
    ROUND(SUM(dp1.hisp_nhopiAlone * w.weight))::numeric AS hisp_nhopiAlone,
    ROUND(SUM(dp1.hisp_otherAlone * w.weight))::numeric AS hisp_otherAlone,
    ROUND(SUM(dp1.hisp_twoOrMore * w.weight))::numeric AS hisp_twoOrMore,
    ROUND(SUM(dp1.total_nonHisp2 * w.weight))::numeric AS total_nonHisp2,
    ROUND(SUM(dp1.nonHisp_whiteAlone * w.weight))::numeric AS nonHisp_whiteAlone,
    ROUND(SUM(dp1.nonHisp_aaAlone * w.weight))::numeric AS nonHisp_aaAlone,
    ROUND(SUM(dp1.nonHisp_aianAlone * w.weight))::numeric AS nonHisp_aianAlone,
    ROUND(SUM(dp1.nonHisp_asianAlone * w.weight))::numeric AS nonHisp_asianAlone,
    ROUND(SUM(dp1.nonHisp_nhopiAlone * w.weight))::numeric AS nonHisp_nhopiAlone,
    ROUND(SUM(dp1.nonHisp_otherAlone * w.weight))::numeric AS nonHisp_otherAlone,
    ROUND(SUM(dp1.nonHisp_twoOrMore * w.weight))::numeric AS nonHisp_twoOrMore,
    ROUND(SUM(dp1.total_pop5 * w.weight))::numeric AS total_pop5,
    ROUND(SUM(dp1.pop_inHH * w.weight))::numeric AS pop_inHH,
    ROUND(SUM(dp1.pop_hh_householder * w.weight))::numeric AS pop_hh_householder,
    ROUND(SUM(dp1.pop_hh_spouse * w.weight))::numeric AS pop_hh_spouse,
    ROUND(SUM(dp1.pop_hh_child * w.weight))::numeric AS pop_hh_child,
    ROUND(SUM(dp1.pop_hh_child_ownChildUnder18 * w.weight))::numeric AS pop_hh_child_ownChildUnder18,
    ROUND(SUM(dp1.pop_hh_otherRelative * w.weight))::numeric AS pop_hh_otherRelative,
    ROUND(SUM(dp1.pop_hh_otherRelative_under18 * w.weight))::numeric AS pop_hh_otherRelative_under18,
    ROUND(SUM(dp1.pop_hh_otherRelative_65over * w.weight))::numeric AS pop_hh_otherRelative_65over,
    ROUND(SUM(dp1.pop_hh_nonrelatives * w.weight))::numeric AS pop_hh_nonrelatives,
    ROUND(SUM(dp1.pop_hh_nonrelatives_under18 * w.weight))::numeric AS pop_hh_nonrelatives_under18,
    ROUND(SUM(dp1.pop_hh_nonrelatives_65over * w.weight))::numeric AS pop_hh_nonrelatives_65over,
    ROUND(SUM(dp1.pop_hh_nonrelatives_unmarriedPartner * w.weight))::numeric AS pop_hh_nonrelatives_unmarriedPartner,
    ROUND(SUM(dp1.pop_in_group * w.weight))::numeric AS pop_in_group,
    ROUND(SUM(dp1.pop_group_inst * w.weight))::numeric AS pop_group_inst,
    ROUND(SUM(dp1.pop_group_inst_male * w.weight))::numeric AS pop_group_inst_male,
    ROUND(SUM(dp1.pop_group_inst_female * w.weight))::numeric AS pop_group_inst_female,
    ROUND(SUM(dp1.pop_group_noninst * w.weight))::numeric AS pop_group_noninst,
    ROUND(SUM(dp1.pop_group_noninst_male * w.weight))::numeric AS pop_group_noninst_male,
    ROUND(SUM(dp1.pop_group_noninst_female * w.weight))::numeric AS pop_group_noninst_female,
    ROUND(SUM(dp1.total_households * w.weight))::numeric AS total_households,
    ROUND(SUM(dp1.hh_family * w.weight))::numeric AS hh_family,
    ROUND(SUM(dp1.hh_family_ownChildrenUnder18 * w.weight))::numeric AS hh_family_ownChildrenUnder18,
    ROUND(SUM(dp1.hh_husbandWifeFam * w.weight))::numeric AS hh_husbandWifeFam,
    ROUND(SUM(dp1.hh_husbandWifeFam_ownChildrenUnder18 * w.weight))::numeric AS hh_husbandWifeFam_ownChildrenUnder18,
    ROUND(SUM(dp1.hh_maleNoWifeFam * w.weight))::numeric AS hh_maleNoWifeFam,
    ROUND(SUM(dp1.hh_maleNoWifeFam_ownChildrenUnder18 * w.weight))::numeric AS hh_maleNoWifeFam_ownChildrenUnder18,
    ROUND(SUM(dp1.hh_femaleNoHusbandFam * w.weight))::numeric AS hh_femaleNoHusbandFam,
    ROUND(SUM(dp1.hh_femaleNoHusbandFam_ownChildrenUnder18 * w.weight))::numeric AS hh_femaleNoHusbandFam_ownChildrenUnder18,
    ROUND(SUM(dp1.hh_nonFamily * w.weight))::numeric AS hh_nonFamily,
    ROUND(SUM(dp1.hh_nonFamily_livingAlone * w.weight))::numeric AS hh_nonFamily_livingAlone,
    ROUND(SUM(dp1.hh_nonFamily_livingAlone_male * w.weight))::numeric AS hh_nonFamily_livingAlone_male,
    ROUND(SUM(dp1.hh_nonFamily_livingAlone_male_65over * w.weight))::numeric AS hh_nonFamily_livingAlone_male_65over,
    ROUND(SUM(dp1.hh_nonFamily_livingAlone_female * w.weight))::numeric AS hh_nonFamily_livingAlone_female,
    ROUND(SUM(dp1.hh_nonFamily_livingAlone_female_65over * w.weight))::numeric AS hh_nonFamily_livingAlone_female_65over,
    ROUND(SUM(dp1.hh_withUnder18 * w.weight))::numeric AS hh_withUnder18,
    ROUND(SUM(dp1.hh_with65over * w.weight))::numeric AS hh_with65over,
    ROUND(SUM(dp1.total_HousingUnits * w.weight))::numeric AS total_HousingUnits,
    ROUND(SUM(dp1.housingUnits_occupied * w.weight))::numeric AS housingUnits_occupied,
    ROUND(SUM(dp1.housingUnits_vacant * w.weight))::numeric AS housingUnits_vacant,
    ROUND(SUM(dp1.housingUnits_vacant_forRent * w.weight))::numeric AS housingUnits_vacant_forRent,
    ROUND(SUM(dp1.housingUnits_vacant_rentedNotOcc * w.weight))::numeric AS housingUnits_vacant_rentedNotOcc,
    ROUND(SUM(dp1.housingUnits_vacant_forSaleOnly * w.weight))::numeric AS housingUnits_vacant_forSaleOnly,
    ROUND(SUM(dp1.housingUnits_vacant_soldNotOcc * w.weight))::numeric AS housingUnits_vacant_soldNotOcc,
    ROUND(SUM(dp1.housingUnits_vacant_occasionalUse * w.weight))::numeric AS housingUnits_vacant_occasionalUse,
    ROUND(SUM(dp1.housingUnits_vacant_otherVacant * w.weight))::numeric AS housingUnits_vacant_otherVacant,
    ROUND(SUM(dp1.total_housingUnits_occupied * w.weight))::numeric AS total_housingUnits_occupied,
    ROUND(SUM(dp1.housingUnits_occupied_ownerOccupied * w.weight))::numeric AS housingUnits_occupied_ownerOccupied,
    ROUND(SUM(dp1.housingUnits_occupied_renterOccupied * w.weight))::numeric AS housingUnits_occupied_renterOccupied,
    ROUND(SUM(dp1.popInOwnerOccupiedHousingUnits * w.weight))::numeric AS popInOwnerOccupiedHousingUnits,
    ROUND(SUM(dp1.popInRenterOccupiedHousingUnits * w.weight))::numeric AS popInRenterOccupiedHousingUnits
  FROM weight AS w
  INNER JOIN demographics.dp1
    ON dp1.geoid10 = w.geoid10
  GROUP BY w.gid
  ORDER BY w.gid
  )

  SELECT 
    gid,
    --median age
    ROUND(demographics.find_median_age(
      total_pop,
      total_under_5,
      total_5_9,
      total_10_14,
      total_15_19,
      total_20_24,
      total_25_29,
      total_30_34,
      total_35_39,
      total_40_44,
      total_45_49,
      total_50_54,
      total_55_59,
      total_60_64,
      total_65_69,
      total_70_74,
      total_75_79,
      total_80_84
      ),2) as median_age,
    --median age male
    ROUND(demographics.find_median_age(
      total_male,
      male_under_5,
      male_5_9,
      male_10_14,
      male_15_19,
      male_20_24,
      male_25_29,
      male_30_34,
      male_35_39,
      male_40_44,
      male_45_49,
      male_50_54,
      male_55_59,
      male_60_64,
      male_65_69,
      male_70_74,
      male_75_79,
      male_80_84
      ),2) as median_age_male,
    --median age female
    ROUND(demographics.find_median_age(
      total_female,
      female_under_5,
      female_5_9,
      female_10_14,
      female_15_19,
      female_20_24,
      female_25_29,
      female_30_34,
      female_35_39,
      female_40_44,
      female_45_49,
      female_50_54,
      female_55_59,
      female_60_64,
      female_65_69,
      female_70_74,
      female_75_79,
      female_80_84
      ),2) as median_age_female,
    --race stats
    ROUND(nonHisp_whiteAlone/total_pop,2) as percent_white_nonhispanic,
    ROUND(nonHisp_aaAlone/total_pop,2) as percent_black_nonhispanic,
    ROUND(nonHisp_aianAlone/total_pop,2) as percent_american_indian_alaskan_native_nonhispanic,
    ROUND(nonHisp_asianAlone/total_pop,2) as percent_asian_nonhispanic,
    ROUND(nonHisp_nhopiAlone/total_pop,2) as percent_native_hawaiian_other_pacific_islander_nonhispanic,
    ROUND(nonHisp_otherAlone/total_pop,2) as percent_other_race_nonhispanic,
    ROUND(total_hisp/total_pop,2) as percent_hispanic,
    --pop in owner occupied housing
    ROUND(popInOwnerOccupiedHousingUnits/total_pop,2) as percent_owner_occupied_housing,
    --pop in renter occupied housing
    ROUND(popInRenterOccupiedHousingUnits/total_pop,2) as percent_renter_occuped_housing
  FROM dem_raw_counts
  ;